server:
  port: 8181

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:9306/busker-authorization?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update